# Generated by Django 2.2 on 2020-11-29 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20201129_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='map_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
