# Generated by Django 2.2 on 2020-11-29 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='category_name',
            new_name='category',
        ),
    ]
