# Generated by Django 2.2 on 2020-11-29 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201129_1451'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogcategory',
            old_name='blog_category_name',
            new_name='category',
        ),
    ]
