# Generated by Django 2.2 on 2020-11-29 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20201129_1452'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogcategory',
            old_name='category',
            new_name='blog_category_name',
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='category',
            new_name='category_name',
        ),
    ]
