# Generated by Django 2.2 on 2020-11-26 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Table of Tag Name', 'verbose_name_plural': 'Table of Tag Name'},
        ),
    ]
