# Generated by Django 2.2 on 2020-11-29 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webprofile', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SocialMediaQuerySet',
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
