# Generated by Django 2.2 on 2020-11-29 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webprofile', '0004_auto_20201129_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutwebprofile',
            name='motto',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
