# Generated by Django 2.2 on 2020-12-01 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import products.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
        ('category', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=25)),
                ('active', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product Color',
                'verbose_name_plural': 'Product Color',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ProductServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=25)),
                ('active', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product Services',
                'verbose_name_plural': 'Product Services',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=25)),
                ('active', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product Size',
                'verbose_name_plural': 'Product Size',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(blank=True, max_length=10, unique=True)),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to=products.utils.upload_image_path)),
                ('video', models.URLField(blank=True, null=True)),
                ('brand', models.CharField(blank=True, max_length=40, null=True)),
                ('Round', models.CharField(blank=True, max_length=40, null=True)),
                ('Fabric', models.CharField(blank=True, max_length=40, null=True)),
                ('Pattern', models.CharField(blank=True, max_length=40, null=True)),
                ('featured', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('quantity', models.IntegerField()),
                ('review', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('like', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_category', to='category.Category')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_color', to='products.ProductColor')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL)),
                ('services', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_services', to='products.ProductServices')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_size', to='products.ProductSize')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_subcategory', to='category.Category')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_tag', to='tags.Tag')),
            ],
            options={
                'verbose_name': 'Product Table',
                'verbose_name_plural': 'Product Table',
            },
        ),
    ]
